name: Package VS Code Extension
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install dependencies
        run: |
          npm install
          npm install -g vsce
      - name: Build the extension
        run: npm install
      - name: Package the extension
        run: vsce package
        shell: bash
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v2
        with:
          name: apicurito-editor-vscode
          path: '*.vsix'
